baseURL : "https://suyogghimire.netlify.app/"
languageCode : en-us
title : "Suyog"
theme : PaperMod

params:


  math: true
  homeInfoParams:
    Title: "Hi,"
    Content: I'm Suyog Ghimire, a second year Computer Engineering student,Here, I share insights and projects on machine learning, programming, and more. Dive into my blogs for tutorials and technical discussions aimed at making complex topics more accessible.
  socialIcons:
    - name: github
      url: "https://github.com/Suyog-16"
    - name: X
      url: "https://twitter.com/__suyog__"
    - name: linkedin
      url: "https://linkedin.com/"


       
  ShowBreadCrumbs: True

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

  disableScrollToTop: false
  showToc : true
  ShowAuthor : true
  enableSearch : true
  
  assets:
    favicon: "android-chrome-192x192.png"       # fallback for browser tab (.ico can be used if available)
    favicon16x16: "android-chrome-192x192.png"  # scaled down by browser automatically
    favicon32x32: "android-chrome-192x192.png"  # scaled down by browser automatically
    apple_touch_icon: "android-chrome-512x512.png"
    safari_pinned_tab: "android-chrome-512x512.png"  # works as a simple fallback
    theme_color: "#ffffff"
    msapplication_TileColor: "#ffffff"
  
 
menu :
  main:
     - identifier: archives
       name : Archives
       url: /archives/
       weight: 30
     - identifier: docs
       name: Resume
       url: https://example.org
       weight: 30
     - identifier: projects
       name: Projects
       url: "https://github.com/Suyog-16"
       weight: 30
markup:
  goldmark:
    renderer:
      unsafe: true

mathjax: true
