baseURL : "https://suyog-ghimire.com.np/"
languageCode : en-us
title : "Suyog"
theme : PaperMod

params:


  math: true
  homeInfoParams:
    Title: "Hi,"
    Content: I'm Suyog Ghimire, a second-year Computer Engineering student at Institute of Engineering(IOE), Paschimanchal campus. I write blogs as a way to learn and document my journey so far I'm especially curious about multimodal AI, vision-and-language models, and how machines can connect perception with understanding. Along the way, I also share thoughts on programming, machine learning, and anything else that sparks my interest.
  socialIcons:
    - name: github
      url: "https://github.com/Suyog-16"
    - name: X
      url: "https://twitter.com/__suyog__"
    - name: linkedin
      url: "https://www.linkedin.com/in/suyog-ghimire-63394a2b2/"


       
  ShowBreadCrumbs: True

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

  disableScrollToTop: false
  showToc : true
  ShowAuthor : true
  enableSearch : true
  
  assets:
    favicon: "android-chrome-192x192.png"       # fallback for browser tab (.ico can be used if available)
    favicon16x16: "android-chrome-192x192.png"  # scaled down by browser automatically
    favicon32x32: "android-chrome-192x192.png"  # scaled down by browser automatically
    apple_touch_icon: "android-chrome-512x512.png"
    safari_pinned_tab: "android-chrome-512x512.png"  # works as a simple fallback
    theme_color: "#ffffff"
    msapplication_TileColor: "#ffffff"
  
 
menu :
  main:
     - identifier: archives
       name : Archives
       url: /archives/
       weight: 30
     - identifier: docs
       name: Resume
       url: "https://drive.google.com/file/d/1dSxZsK8xPPDeFpjWan3aMsp-Ak6wfPVS/view"
       weight: 30
     - identifier: projects
       name: Projects
       url: "https://github.com/Suyog-16"
       weight: 30
markup:
  goldmark:
    renderer:
      unsafe: true

mathjax: true
